-- AccountSettings basics {{{
AccountSettings = {}

AccountSettings.name = "AccountSettings"
AccountSettings.version = 1.0
AccountSettings.savedName = "AccountSettings_SV"
AccountSettings.displayName = "|cff8555Account Settings|r"
AccountSettings.str = ""

AccountSettings.Default = {}
AccountSettings.Default.sync = true
AccountSettings.Default.log = false
AccountSettings.Default.debug = false
AccountSettings.Default.settings = {}
AccountSettings.Default.settingsBool = {}
AccountSettings.Default.chatColors = {}
AccountSettings.Default.tracked = false
AccountSettings.Default.showChatIcon = true

AccountSettings.OKAY_COLOR = "44ff44"
AccountSettings.ERROR_COLOR = "ff4444"
AccountSettings.DEBUG_COLOR = "ffff44"

-- End AccountSettings basics }}}

-- ESO Settings {{{
AccountSettings.ChatColors = {
    CHAT_CATEGORY_COMBAT_ALLIANCE_POINTS,
    CHAT_CATEGORY_COMBAT_BLOCK_ABSORBED_DEFEND,
    CHAT_CATEGORY_COMBAT_DEATH,
    CHAT_CATEGORY_COMBAT_DIRECT_DAMAGE,
    CHAT_CATEGORY_COMBAT_DIRECT_HEAL,
    CHAT_CATEGORY_COMBAT_DODGE_PARRY_MISS,
    CHAT_CATEGORY_COMBAT_DOT,
    CHAT_CATEGORY_COMBAT_DRAIN,
    CHAT_CATEGORY_COMBAT_ENERGIZE,
    CHAT_CATEGORY_COMBAT_EXPERIENCE,
    CHAT_CATEGORY_COMBAT_GAINED_EFFECT,
    CHAT_CATEGORY_COMBAT_HOT,
    CHAT_CATEGORY_COMBAT_LOST_EFFECT,
    CHAT_CATEGORY_COMBAT_OTHER,
    CHAT_CATEGORY_COMBAT_RANK_POINTS,
    CHAT_CATEGORY_COMBAT_RESIST,
    CHAT_CATEGORY_COMBAT_TELVAR_STONES,
    CHAT_CATEGORY_EMOTE,
    CHAT_CATEGORY_GUILD_1,
    CHAT_CATEGORY_GUILD_2,
    CHAT_CATEGORY_GUILD_3,
    CHAT_CATEGORY_GUILD_4,
    CHAT_CATEGORY_GUILD_5,
    CHAT_CATEGORY_MONSTER_EMOTE,
    CHAT_CATEGORY_MONSTER_SAY,
    CHAT_CATEGORY_MONSTER_WHISPER,
    CHAT_CATEGORY_MONSTER_YELL,
    CHAT_CATEGORY_OFFICER_1,
    CHAT_CATEGORY_OFFICER_2,
    CHAT_CATEGORY_OFFICER_3,
    CHAT_CATEGORY_OFFICER_4,
    CHAT_CATEGORY_OFFICER_5,
    CHAT_CATEGORY_PARTY,
    CHAT_CATEGORY_SAY,
    CHAT_CATEGORY_SYSTEM,
    CHAT_CATEGORY_WHISPER_INCOMING,
    CHAT_CATEGORY_WHISPER_OUTGOING,
    CHAT_CATEGORY_YELL,
    CHAT_CATEGORY_ZONE,
    CHAT_CATEGORY_ZONE_ENGLISH,
    CHAT_CATEGORY_ZONE_FRENCH,
    CHAT_CATEGORY_ZONE_GERMAN,
    CHAT_CATEGORY_ZONE_JAPANESE,
}

AccountSettings.SettingSystemType = {
    SETTING_TYPE_ACTIVE_COMBAT_TIP,
    SETTING_TYPE_AUDIO,
    SETTING_TYPE_BUFFS,
    SETTING_TYPE_CAMERA,
    SETTING_TYPE_CHAT_BUBBLE,
    SETTING_TYPE_COMBAT,
    SETTING_TYPE_GAMEPAD,
    SETTING_TYPE_GRAPHICS,
    SETTING_TYPE_IN_WORLD,
    SETTING_TYPE_LANGUAGE,
    SETTING_TYPE_LOOT,
    SETTING_TYPE_NAMEPLATES,
    -- SETTING_TYPE_SUBTITLES,
    SETTING_TYPE_TUTORIAL,
    SETTING_TYPE_UI,
}

AccountSettings.SettingSystemTypeString = {
    [SETTING_TYPE_ACTIVE_COMBAT_TIP] = "SETTING_TYPE_ACTIVE_COMBAT_TIP",
    [SETTING_TYPE_AUDIO            ] = "SETTING_TYPE_AUDIO",
    [SETTING_TYPE_BUFFS            ] = "SETTING_TYPE_BUFFS",
    [SETTING_TYPE_CAMERA           ] = "SETTING_TYPE_CAMERA",
    [SETTING_TYPE_CHAT_BUBBLE      ] = "SETTING_TYPE_CHAT_BUBBLE",
    [SETTING_TYPE_COMBAT           ] = "SETTING_TYPE_COMBAT",
    [SETTING_TYPE_GAMEPAD          ] = "SETTING_TYPE_GAMEPAD",
    [SETTING_TYPE_GRAPHICS         ] = "SETTING_TYPE_GRAPHICS",
    [SETTING_TYPE_IN_WORLD         ] = "SETTING_TYPE_IN_WORLD",
    [SETTING_TYPE_LANGUAGE         ] = "SETTING_TYPE_LANGUAGE",
    [SETTING_TYPE_LOOT             ] = "SETTING_TYPE_LOOT",
    [SETTING_TYPE_NAMEPLATES       ] = "SETTING_TYPE_NAMEPLATES",
    -- [SETTING_TYPE_SUBTITLES        ] = "SETTING_TYPE_SUBTITLES",
    [SETTING_TYPE_TUTORIAL         ] = "SETTING_TYPE_TUTORIAL",
    [SETTING_TYPE_UI               ] = "SETTING_TYPE_UI",
}

AccountSettings.SettingIds = {
    [SETTING_TYPE_ACTIVE_COMBAT_TIP] = {
        0
    },

    [SETTING_TYPE_AUDIO] = {
        AUDIO_SETTING_AMBIENT_VOLUME,
        AUDIO_SETTING_AUDIO_VOLUME,
        AUDIO_SETTING_BACKGROUND_AUDIO,
        AUDIO_SETTING_FOOTSTEPS_VOLUME,
        AUDIO_SETTING_MUSIC_ENABLED,
        AUDIO_SETTING_MUSIC_VOLUME,
        AUDIO_SETTING_SFX_ENABLED,
        AUDIO_SETTING_SFX_VOLUME,
        AUDIO_SETTING_UI_VOLUME,
        AUDIO_SETTING_VOICE_CHAT_VOLUME,
        AUDIO_SETTING_VO_VOLUME,
    },

    [SETTING_TYPE_BUFFS] = {
        BUFFS_SETTING_ALL_ENABLED,
        BUFFS_SETTING_BUFFS_ENABLED,
        BUFFS_SETTING_BUFFS_ENABLED_FOR_SELF,
        BUFFS_SETTING_BUFFS_ENABLED_FOR_TARGET,
        BUFFS_SETTING_DEBUFFS_ENABLED,
        BUFFS_SETTING_DEBUFFS_ENABLED_FOR_SELF,
        BUFFS_SETTING_DEBUFFS_ENABLED_FOR_TARGET,
        BUFFS_SETTING_DEBUFFS_ENABLED_FOR_TARGET_FROM_OTHERS,
        BUFFS_SETTING_LONG_EFFECTS,
        BUFFS_SETTING_PERMANENT_EFFECTS,
    },

    [SETTING_TYPE_CAMERA] = {
        CAMERA_SETTING_ASSASSINATION_CAMERA,
        CAMERA_SETTING_FIRST_PERSON_FIELD_OF_VIEW,
        CAMERA_SETTING_FIRST_PERSON_HEAD_BOB,
        CAMERA_SETTING_FOV_CHANGES_ALLOWED,
        CAMERA_SETTING_INVERT_Y,
        CAMERA_SETTING_SCREEN_SHAKE,
        CAMERA_SETTING_SENSITIVITY_FIRST_PERSON,
        CAMERA_SETTING_SENSITIVITY_THIRD_PERSON,
        CAMERA_SETTING_SMOOTHING,
        CAMERA_SETTING_THIRD_PERSON_FIELD_OF_VIEW,
        CAMERA_SETTING_THIRD_PERSON_HORIZONTAL_OFFSET,
        CAMERA_SETTING_THIRD_PERSON_HORIZONTAL_POSITION_MULTIPLIER,
        CAMERA_SETTING_THIRD_PERSON_SIEGE_WEAPONRY,
        CAMERA_SETTING_THIRD_PERSON_VERTICAL_OFFSET,
    },

    [SETTING_TYPE_CHAT_BUBBLE] = {
        CHAT_BUBBLE_SETTING_ENABLED,
        CHAT_BUBBLE_SETTING_ENABLED_FOR_LOCAL_PLAYER,
        CHAT_BUBBLE_SETTING_ENABLED_ONLY_FROM_CONTACTS,
        CHAT_BUBBLE_SETTING_SPEED_MODIFIER,
    },

    [SETTING_TYPE_COMBAT] = {
        COMBAT_SETTING_CLAMP_GROUND_TARGET_ENABLED,
        COMBAT_SETTING_MONSTER_TELLS_COLOR_SWAP_ENABLED,
        COMBAT_SETTING_MONSTER_TELLS_ENABLED,
        COMBAT_SETTING_MONSTER_TELLS_ENEMY_BRIGHTNESS,
        COMBAT_SETTING_MONSTER_TELLS_ENEMY_COLOR,
        COMBAT_SETTING_MONSTER_TELLS_FRIENDLY_BRIGHTNESS,
        COMBAT_SETTING_MONSTER_TELLS_FRIENDLY_COLOR,
        COMBAT_SETTING_PREVENT_ATTACKING_INNOCENTS,
        COMBAT_SETTING_QUICK_CAST_GROUND_ABILITIES,
        COMBAT_SETTING_ROLL_DODGE_DOUBLE_TAP,
        COMBAT_SETTING_ROLL_DODGE_WINDOW,
        COMBAT_SETTING_SCROLLING_COMBAT_TEXT_ENABLED,
        COMBAT_SETTING_SCT_INCOMING_DAMAGE_ENABLED,
        COMBAT_SETTING_SCT_INCOMING_DOT_ENABLED,
        COMBAT_SETTING_SCT_INCOMING_ENABLED,
        COMBAT_SETTING_SCT_INCOMING_HEALING_ENABLED,
        COMBAT_SETTING_SCT_INCOMING_HOT_ENABLED,
        COMBAT_SETTING_SCT_INCOMING_PET_DAMAGE_ENABLED,
        COMBAT_SETTING_SCT_INCOMING_PET_DOT_ENABLED,
        COMBAT_SETTING_SCT_INCOMING_POINT_GAINS_ENABLED,
        COMBAT_SETTING_SCT_INCOMING_STATUS_EFFECTS_ENABLED,
        COMBAT_SETTING_SCT_OUTGOING_DAMAGE_ENABLED,
        COMBAT_SETTING_SCT_OUTGOING_DOT_ENABLED,
        COMBAT_SETTING_SCT_OUTGOING_ENABLED,
        COMBAT_SETTING_SCT_OUTGOING_HEALING_ENABLED,
        COMBAT_SETTING_SCT_OUTGOING_HOT_ENABLED,
        COMBAT_SETTING_SCT_OUTGOING_PET_DAMAGE_ENABLED,
        COMBAT_SETTING_SCT_OUTGOING_PET_DOT_ENABLED,
        COMBAT_SETTING_SCT_OUTGOING_PET_HEALING_ENABLED,
        COMBAT_SETTING_SCT_OUTGOING_PET_HOT_ENABLED,
        COMBAT_SETTING_SCT_OUTGOING_STATUS_EFFECTS_ENABLED,
        COMBAT_SETTING_ENCOUNTER_LOG_APPEAR_ANONYMOUS
    },

    [SETTING_TYPE_GAMEPAD] = {
        GAMEPAD_SETTING_CAMERA_SENSITIVITY,
        GAMEPAD_SETTING_GAMEPAD_TEMPLATE,
        GAMEPAD_SETTING_INVERT_Y,
        GAMEPAD_SETTING_VIBRATION,
    },

    [SETTING_TYPE_GRAPHICS] = {
        GRAPHICS_SETTING_AMBIENT_OCCLUSION_TYPE,
        GRAPHICS_SETTING_ANTI_ALIASING,
        GRAPHICS_SETTING_BLOOM,
        GRAPHICS_SETTING_CLUTTER_2D,
        GRAPHICS_SETTING_CONSOLE_ENHANCED_RENDER_QUALITY,
        GRAPHICS_SETTING_DEPTH_OF_FIELD,
        GRAPHICS_SETTING_DISTORTION,
        GRAPHICS_SETTING_FULLSCREEN,
        GRAPHICS_SETTING_GAMMA_ADJUSTMENT,
        GRAPHICS_SETTING_GOD_RAYS,
        GRAPHICS_SETTING_HDR_BRIGHTNESS,
        GRAPHICS_SETTING_MIP_LOAD_SKIP_LEVELS,
        GRAPHICS_SETTING_PFX_GLOBAL_MAXIMUM,
        GRAPHICS_SETTING_PFX_SUPPRESS_DISTANCE,
        GRAPHICS_SETTING_PRESETS,
        GRAPHICS_SETTING_REFLECTION_QUALITY,
        GRAPHICS_SETTING_RESOLUTION,
        GRAPHICS_SETTING_SHADOWS,
        GRAPHICS_SETTING_SHOW_ADDITIONAL_ALLY_EFFECTS,
        GRAPHICS_SETTING_SUB_SAMPLING,
        GRAPHICS_SETTING_VIEW_DISTANCE,
        GRAPHICS_SETTING_VSYNC,
    },

    [SETTING_TYPE_IN_WORLD] = {
        IN_WORLD_UI_SETTING_DEFAULT_SOUL_GEM,
        IN_WORLD_UI_SETTING_FOOT_INVERSE_KINEMATICS,
        IN_WORLD_UI_SETTING_GLOW_THICKNESS,
        IN_WORLD_UI_SETTING_HIDE_MOUNT_INVENTORY_UPGRADE,
        IN_WORLD_UI_SETTING_HIDE_MOUNT_SPEED_UPGRADE,
        IN_WORLD_UI_SETTING_HIDE_MOUNT_STAMINA_UPGRADE,
        IN_WORLD_UI_SETTING_HIDE_POLYMORPH_HELM,
        IN_WORLD_UI_SETTING_INTERACTABLE_GLOW_ENABLED,
        IN_WORLD_UI_SETTING_INTERACTABLE_GLOW_INTENSITY,
        IN_WORLD_UI_SETTING_TARGET_GLOW_ENABLED,
        IN_WORLD_UI_SETTING_TARGET_GLOW_INTENSITY,
    },

    [SETTING_TYPE_LANGUAGE] = {
        LANGUAGE_SETTING_USE_PROFANITY_FILTER,
    },

    [SETTING_TYPE_LOOT] = {
        LOOT_SETTING_AOE_LOOT,
        LOOT_SETTING_AUTO_ADD_TO_CRAFT_BAG,
        LOOT_SETTING_AUTO_LOOT,
        LOOT_SETTING_AUTO_LOOT_STOLEN,
        LOOT_SETTING_LOOT_HISTORY,
    },

    [SETTING_TYPE_NAMEPLATES] = {
        NAMEPLATE_TYPE_ALLIANCE_INDICATORS,
        NAMEPLATE_TYPE_ALL_HEALTHBARS,
        NAMEPLATE_TYPE_ALL_NAMEPLATES,
        NAMEPLATE_TYPE_ENEMY_NPC_HEALTHBARS,
        NAMEPLATE_TYPE_ENEMY_NPC_HEALTHBARS_HIGHLIGHT,
        NAMEPLATE_TYPE_ENEMY_NPC_NAMEPLATES,
        NAMEPLATE_TYPE_ENEMY_NPC_NAMEPLATES_HIGHLIGHT,
        NAMEPLATE_TYPE_ENEMY_PLAYER_HEALTHBARS,
        NAMEPLATE_TYPE_ENEMY_PLAYER_HEALTHBARS_HIGHLIGHT,
        NAMEPLATE_TYPE_ENEMY_PLAYER_NAMEPLATES,
        NAMEPLATE_TYPE_ENEMY_PLAYER_NAMEPLATES_HIGHLIGHT,
        NAMEPLATE_TYPE_FOLLOWER_INDICATORS,
        NAMEPLATE_TYPE_FRIENDLY_NPC_HEALTHBARS,
        NAMEPLATE_TYPE_FRIENDLY_NPC_HEALTHBARS_HIGHLIGHT,
        NAMEPLATE_TYPE_FRIENDLY_NPC_NAMEPLATES,
        NAMEPLATE_TYPE_FRIENDLY_NPC_NAMEPLATES_HIGHLIGHT,
        NAMEPLATE_TYPE_FRIENDLY_PLAYER_HEALTHBARS,
        NAMEPLATE_TYPE_FRIENDLY_PLAYER_HEALTHBARS_HIGHLIGHT,
        NAMEPLATE_TYPE_FRIENDLY_PLAYER_NAMEPLATES,
        NAMEPLATE_TYPE_FRIENDLY_PLAYER_NAMEPLATES_HIGHLIGHT,
        NAMEPLATE_TYPE_GROUP_INDICATORS,
        NAMEPLATE_TYPE_GROUP_MEMBER_HEALTHBARS,
        NAMEPLATE_TYPE_GROUP_MEMBER_HEALTHBARS_HIGHLIGHT,
        NAMEPLATE_TYPE_GROUP_MEMBER_NAMEPLATES,
        NAMEPLATE_TYPE_GROUP_MEMBER_NAMEPLATES_HIGHLIGHT,
        NAMEPLATE_TYPE_HEALTHBAR_ALIGNMENT,
        NAMEPLATE_TYPE_HEALTHBAR_CHASE_BAR,
        NAMEPLATE_TYPE_HEALTHBAR_FRAME_BORDER,
        NAMEPLATE_TYPE_NEUTRAL_NPC_HEALTHBARS,
        NAMEPLATE_TYPE_NEUTRAL_NPC_HEALTHBARS_HIGHLIGHT,
        NAMEPLATE_TYPE_NEUTRAL_NPC_NAMEPLATES,
        NAMEPLATE_TYPE_NEUTRAL_NPC_NAMEPLATES_HIGHLIGHT,
        NAMEPLATE_TYPE_PLAYER_HEALTHBAR,
        NAMEPLATE_TYPE_PLAYER_HEALTHBAR_HIGHLIGHT,
        NAMEPLATE_TYPE_PLAYER_NAMEPLATE,
        NAMEPLATE_TYPE_PLAYER_NAMEPLATE_HIGHLIGHT,
        NAMEPLATE_TYPE_RESURRECT_INDICATORS,
        NAMEPLATE_TYPE_SHOW_PLAYER_GUILDS,
        NAMEPLATE_TYPE_SHOW_PLAYER_TITLES,
    },
    -- [SETTING_TYPE_SUBTITLES] = {
        -- SUBTITLE_SETTING_ENABLED
    -- },

    [SETTING_TYPE_TUTORIAL] = {
        TUTORIAL_ENABLED_SETTING_ID,
        OPTIONS_CUSTOM_SETTING_RESET_TUTORIALS
    },

    [SETTING_TYPE_UI] = {
        UI_SETTING_AUTO_DECLINE_DUEL_INVITES,
        UI_SETTING_COMPASS_ACTIVE_QUESTS,
        UI_SETTING_COMPASS_QUEST_GIVERS,
        UI_SETTING_CUSTOM_SCALE,
        UI_SETTING_FRAMERATE_LATENCY_LOCK,
        UI_SETTING_GAMEPAD_CHAT_HUD_ENABLED,
        UI_SETTING_PRIMARY_PLAYER_NAME_GAMEPAD,
        UI_SETTING_PRIMARY_PLAYER_NAME_KEYBOARD,
        UI_SETTING_RESOURCE_NUMBERS,
        UI_SETTING_RETURN_CURSOR_ON_CHAT_FOCUS,
        UI_SETTING_SHOW_ACTION_BAR,
        UI_SETTING_SHOW_ARMOR_INDICATOR,
        UI_SETTING_SHOW_AVA_NOTIFICATIONS,
        UI_SETTING_SHOW_FRAMERATE,
        UI_SETTING_SHOW_LATENCY,
        UI_SETTING_SHOW_LEADERBOARD_NOTIFICATIONS,
        UI_SETTING_SHOW_QUEST_BESTOWER_INDICATORS,
        UI_SETTING_SHOW_QUEST_TRACKER,
        UI_SETTING_SHOW_RAID_LIVES,
        UI_SETTING_SHOW_RESOURCE_BARS,
        UI_SETTING_SHOW_WEAPON_INDICATOR,
        UI_SETTING_SOCIAL_LIST_HIDE_OFFLINE,
        UI_SETTING_ULTIMATE_NUMBER,
        UI_SETTING_USE_CUSTOM_SCALE,
    },
}

AccountSettings.SettingStrings = {
    [SETTING_TYPE_ACTIVE_COMBAT_TIP] = {
        [0] = SI_INTERFACE_OPTIONS_ACT_SETTING_LABEL
    },

    [SETTING_TYPE_AUDIO] = {
        [AUDIO_SETTING_AMBIENT_VOLUME]    = SI_AUDIO_OPTIONS_AMBIENT_VOLUME,
        [AUDIO_SETTING_AUDIO_VOLUME]      = SI_AUDIO_OPTIONS_MASTER_VOLUME,
        [AUDIO_SETTING_BACKGROUND_AUDIO]  = SI_AUDIO_OPTIONS_BACKGROUND_AUDIO,
        [AUDIO_SETTING_FOOTSTEPS_VOLUME]  = SI_AUDIO_OPTIONS_FOOTSTEPS_VOLUME,
        [AUDIO_SETTING_MUSIC_ENABLED]     = SI_AUDIO_OPTIONS_MUSIC_ENABLED,
        [AUDIO_SETTING_MUSIC_VOLUME]      = SI_AUDIO_OPTIONS_MUSIC_VOLUME,
        [AUDIO_SETTING_SFX_ENABLED]       = SI_AUDIO_OPTIONS_SOUND_ENABLED,
        [AUDIO_SETTING_SFX_VOLUME]        = SI_AUDIO_OPTIONS_SFX_VOLUME,
        [AUDIO_SETTING_UI_VOLUME]         = SI_AUDIO_OPTIONS_UI_VOLUME,
        [AUDIO_SETTING_VOICE_CHAT_VOLUME] = SI_GAMEPAD_AUDIO_OPTIONS_VOICECHAT_VOLUME,
        [AUDIO_SETTING_VO_VOLUME]         = SI_AUDIO_OPTIONS_VO_VOLUME,
    },

    [SETTING_TYPE_BUFFS] = {
        [BUFFS_SETTING_ALL_ENABLED                           ]  = SI_BUFFS_OPTIONS_ALL_ENABLED,
        [BUFFS_SETTING_BUFFS_ENABLED                         ]  = SI_BUFFS_OPTIONS_BUFFS_ENABLED,
        [BUFFS_SETTING_BUFFS_ENABLED_FOR_SELF                ]  = SI_BUFFS_OPTIONS_BUFFS_ENABLED_FOR_SELF,
        [BUFFS_SETTING_BUFFS_ENABLED_FOR_TARGET              ]  = SI_BUFFS_OPTIONS_BUFFS_ENABLED_FOR_TARGET,
        [BUFFS_SETTING_DEBUFFS_ENABLED                       ]  = SI_BUFFS_OPTIONS_DEBUFFS_ENABLED,
        [BUFFS_SETTING_DEBUFFS_ENABLED_FOR_SELF              ]  = SI_BUFFS_OPTIONS_DEBUFFS_ENABLED_FOR_SELF,
        [BUFFS_SETTING_DEBUFFS_ENABLED_FOR_TARGET            ]  = SI_BUFFS_OPTIONS_DEBUFFS_ENABLED_FOR_TARGET,
        [BUFFS_SETTING_DEBUFFS_ENABLED_FOR_TARGET_FROM_OTHERS]  = SI_BUFFS_OPTIONS_DEBUFFS_ENABLED_FOR_TARGET_FROM_OTHERS,
        [BUFFS_SETTING_LONG_EFFECTS                          ]  = SI_BUFFS_OPTIONS_LONG_EFFECTS,
        [BUFFS_SETTING_PERMANENT_EFFECTS                     ]  = SI_BUFFS_OPTIONS_PERMANENT_EFFECTS,
    },

    [SETTING_TYPE_CAMERA] = {
        [CAMERA_SETTING_ASSASSINATION_CAMERA                       ] = SI_INTERFACE_OPTIONS_CAMERA_ASSASSINATION_CAMERA,
        [CAMERA_SETTING_FIRST_PERSON_FIELD_OF_VIEW                 ] = SI_INTERFACE_OPTIONS_CAMERA_FIRST_PERSON_FOV,
        [CAMERA_SETTING_FIRST_PERSON_HEAD_BOB                      ] = SI_INTERFACE_OPTIONS_CAMERA_FIRST_PERSON_BOB,
        [CAMERA_SETTING_FOV_CHANGES_ALLOWED                        ] = SI_INTERFACE_OPTIONS_CAMERA_FOV_CHANGES,
        [CAMERA_SETTING_INVERT_Y                                   ] = SI_INTERFACE_OPTIONS_CAMERA_INVERT_Y,
        [CAMERA_SETTING_SCREEN_SHAKE                               ] = SI_INTERFACE_OPTIONS_CAMERA_SCREEN_SHAKE,
        [CAMERA_SETTING_SENSITIVITY_FIRST_PERSON                   ] = SI_INTERFACE_OPTIONS_CAMERA_SENSITIVITY_FIRST_PERSON,
        [CAMERA_SETTING_SENSITIVITY_THIRD_PERSON                   ] = SI_INTERFACE_OPTIONS_CAMERA_SENSITIVITY_THIRD_PERSON,
        [CAMERA_SETTING_SMOOTHING                                  ] = SI_INTERFACE_OPTIONS_CAMERA_SMOOTHING,
        [CAMERA_SETTING_THIRD_PERSON_FIELD_OF_VIEW                 ] = SI_INTERFACE_OPTIONS_CAMERA_THIRD_PERSON_FOV,
        [CAMERA_SETTING_THIRD_PERSON_HORIZONTAL_OFFSET             ] = SI_INTERFACE_OPTIONS_CAMERA_THIRD_PERSON_HORIZONTAL_OFFSET,
        [CAMERA_SETTING_THIRD_PERSON_HORIZONTAL_POSITION_MULTIPLIER] = SI_INTERFACE_OPTIONS_CAMERA_THIRD_PERSON_HORIZONTAL_POSITION_MULTIPLIER,
        [CAMERA_SETTING_THIRD_PERSON_SIEGE_WEAPONRY                ] = SI_INTERFACE_OPTIONS_CAMERA_THIRD_PERSON_SIEGE_WEAPONRY,
        [CAMERA_SETTING_THIRD_PERSON_VERTICAL_OFFSET               ] = SI_INTERFACE_OPTIONS_CAMERA_THIRD_PERSON_VERTICAL_OFFSET,
    },

    [SETTING_TYPE_CHAT_BUBBLE] = {
        [CHAT_BUBBLE_SETTING_ENABLED                   ] = SI_INTERFACE_OPTIONS_CHAT_BUBBLES,
        [CHAT_BUBBLE_SETTING_ENABLED_FOR_LOCAL_PLAYER  ] = SI_INTERFACE_OPTIONS_CHAT_BUBBLES_SELF,
        [CHAT_BUBBLE_SETTING_ENABLED_ONLY_FROM_CONTACTS] = SI_INTERFACE_OPTIONS_CHAT_BUBBLES_ONLY_KNOWN,
        [CHAT_BUBBLE_SETTING_SPEED_MODIFIER            ] = SI_INTERFACE_OPTIONS_CHAT_BUBBLES_FADE_RATE,
    },

    [SETTING_TYPE_COMBAT] = {
        [COMBAT_SETTING_CLAMP_GROUND_TARGET_ENABLED        ] = SI_INTERFACE_OPTIONS_COMBAT_CLAMP_GROUND_TARGET_ENABLED,
        [COMBAT_SETTING_MONSTER_TELLS_COLOR_SWAP_ENABLED   ] = SI_INTERFACE_OPTIONS_COMBAT_MONSTER_TELLS_COLOR_SWAP_ENABLED,
        [COMBAT_SETTING_MONSTER_TELLS_ENABLED              ] = SI_INTERFACE_OPTIONS_COMBAT_MONSTER_TELLS_ENABLE,
        [COMBAT_SETTING_MONSTER_TELLS_ENEMY_BRIGHTNESS     ] = SI_INTERFACE_OPTIONS_COMBAT_MONSTER_TELLS_ENEMY_BRIGHTNESS,
        [COMBAT_SETTING_MONSTER_TELLS_ENEMY_COLOR          ] = SI_INTERFACE_OPTIONS_COMBAT_MONSTER_TELLS_ENEMY_COLOR,
        [COMBAT_SETTING_MONSTER_TELLS_FRIENDLY_BRIGHTNESS  ] = SI_INTERFACE_OPTIONS_COMBAT_MONSTER_TELLS_FRIENDLY_BRIGHTNESS,
        [COMBAT_SETTING_MONSTER_TELLS_FRIENDLY_COLOR       ] = SI_INTERFACE_OPTIONS_COMBAT_MONSTER_TELLS_FRIENDLY_COLOR,
        [COMBAT_SETTING_PREVENT_ATTACKING_INNOCENTS        ] = SI_INTERFACE_OPTIONS_COMBAT_PREVENT_ATTACKING_INNOCENTS,
        [COMBAT_SETTING_QUICK_CAST_GROUND_ABILITIES        ] = SI_INTERFACE_OPTIONS_COMBAT_QUICK_CAST_GROUND_ABILITIES,
        [COMBAT_SETTING_ROLL_DODGE_DOUBLE_TAP              ] = SI_INTERFACE_OPTIONS_COMBAT_ROLL_DODGE_ENABLED,
        [COMBAT_SETTING_ROLL_DODGE_WINDOW                  ] = SI_INTERFACE_OPTIONS_COMBAT_ROLL_DODGE_WINDOW,
        [COMBAT_SETTING_SCROLLING_COMBAT_TEXT_ENABLED      ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_ENABLED,
        [COMBAT_SETTING_SCT_INCOMING_DAMAGE_ENABLED        ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_DAMAGE_ENABLED,
        [COMBAT_SETTING_SCT_INCOMING_DOT_ENABLED           ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_DOT_ENABLED,
        [COMBAT_SETTING_SCT_INCOMING_ENABLED               ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_ENABLED,
        [COMBAT_SETTING_SCT_INCOMING_HEALING_ENABLED       ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_HEALING_ENABLED,
        [COMBAT_SETTING_SCT_INCOMING_HOT_ENABLED           ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_HOT_ENABLED,
        [COMBAT_SETTING_SCT_INCOMING_PET_DAMAGE_ENABLED    ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_PET_DAMAGE_ENABLED,
        [COMBAT_SETTING_SCT_INCOMING_PET_DOT_ENABLED       ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_PET_DOT_ENABLED,
        [COMBAT_SETTING_SCT_INCOMING_POINT_GAINS_ENABLED   ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_POINT_GAINS_ENABLED,
        [COMBAT_SETTING_SCT_INCOMING_STATUS_EFFECTS_ENABLED] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_STATUS_EFFECTS_ENABLED,
        [COMBAT_SETTING_SCT_OUTGOING_DAMAGE_ENABLED        ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_DAMAGE_ENABLED,
        [COMBAT_SETTING_SCT_OUTGOING_DOT_ENABLED           ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_DOT_ENABLED,
        [COMBAT_SETTING_SCT_OUTGOING_ENABLED               ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_ENABLED,
        [COMBAT_SETTING_SCT_OUTGOING_HEALING_ENABLED       ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_HEALING_ENABLED,
        [COMBAT_SETTING_SCT_OUTGOING_HOT_ENABLED           ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_HOT_ENABLED,
        [COMBAT_SETTING_SCT_OUTGOING_PET_DAMAGE_ENABLED    ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_PET_DAMAGE_ENABLED,
        [COMBAT_SETTING_SCT_OUTGOING_PET_DOT_ENABLED       ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_PET_DOT_ENABLED,
        [COMBAT_SETTING_SCT_OUTGOING_PET_HEALING_ENABLED   ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_PET_HEALING_ENABLED,
        [COMBAT_SETTING_SCT_OUTGOING_PET_HOT_ENABLED       ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_PET_HOT_ENABLED,
        [COMBAT_SETTING_SCT_OUTGOING_STATUS_EFFECTS_ENABLED] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_STATUS_EFFECTS_ENABLED,
        [COMBAT_SETTING_ENCOUNTER_LOG_APPEAR_ANONYMOUS     ] = SI_INTERFACE_OPTIONS_COMBAT_ENCOUNTER_LOG_APPEAR_ANONYMOUS
    },

    [SETTING_TYPE_GAMEPAD] = {
        [GAMEPAD_SETTING_CAMERA_SENSITIVITY] = SI_GAMEPAD_OPTIONS_CAMERA_SENSITIVITY,
        [GAMEPAD_SETTING_GAMEPAD_TEMPLATE  ] = SI_GAMEPAD_OPTIONS_TEMPLATES,
        [GAMEPAD_SETTING_INVERT_Y          ] = SI_GAMEPAD_OPTIONS_INVERT_Y,
        [GAMEPAD_SETTING_VIBRATION         ] = SI_GAMEPAD_OPTIONS_CAMERA_VIBRATION,
    },

    [SETTING_TYPE_GRAPHICS] = {
        [GRAPHICS_SETTING_AMBIENT_OCCLUSION_TYPE         ] = SI_GRAPHICS_OPTIONS_VIDEO_AMBIENT_OCCLUSION_TYPE,
        [GRAPHICS_SETTING_ANTI_ALIASING                  ] = SI_GRAPHICS_OPTIONS_VIDEO_ANTI_ALIASING,
        [GRAPHICS_SETTING_BLOOM                          ] = SI_GRAPHICS_OPTIONS_VIDEO_BLOOM,
        [GRAPHICS_SETTING_CLUTTER_2D                     ] = SI_GRAPHICS_OPTIONS_VIDEO_CLUTTER_2D,
        [GRAPHICS_SETTING_CONSOLE_ENHANCED_RENDER_QUALITY] = SI_GRAPHICS_OPTIONS_CONSOLE_ENHANCED_RENDER_QUALITY,
        [GRAPHICS_SETTING_DEPTH_OF_FIELD                 ] = SI_GRAPHICS_OPTIONS_VIDEO_DEPTH_OF_FIELD,
        [GRAPHICS_SETTING_DISTORTION                     ] = SI_GRAPHICS_OPTIONS_VIDEO_DISTORTION,
        [GRAPHICS_SETTING_FULLSCREEN                     ] = SI_GRAPHICS_OPTIONS_VIDEO_DISPLAY_MODE,
        [GRAPHICS_SETTING_GAMMA_ADJUSTMENT               ] = SI_GRAPHICS_OPTIONS_VIDEO_GAMMA_ADJUSTMENT,
        [GRAPHICS_SETTING_GOD_RAYS                       ] = SI_GRAPHICS_OPTIONS_VIDEO_GOD_RAYS,
        [GRAPHICS_SETTING_HDR_BRIGHTNESS                 ] = SI_GRAPHICS_OPTIONS_VIDEO_HDR_BRIGHTNESS,
        [GRAPHICS_SETTING_MIP_LOAD_SKIP_LEVELS           ] = SI_GRAPHICS_OPTIONS_VIDEO_TEXTURE_RES,
        [GRAPHICS_SETTING_PFX_GLOBAL_MAXIMUM             ] = SI_GRAPHICS_OPTIONS_VIDEO_MAXIMUM_PARTICLE_SYSTEMS,
        [GRAPHICS_SETTING_PFX_SUPPRESS_DISTANCE          ] = SI_GRAPHICS_OPTIONS_VIDEO_PARTICLE_SUPPRESSION_DISTANCE,
        [GRAPHICS_SETTING_PRESETS                        ] = SI_GRAPHICS_OPTIONS_VIDEO_PRESETS,
        [GRAPHICS_SETTING_REFLECTION_QUALITY             ] = SI_GRAPHICS_OPTIONS_VIDEO_REFLECTION_QUALITY,
        [GRAPHICS_SETTING_RESOLUTION                     ] = SI_GRAPHICS_OPTIONS_VIDEO_RESOLUTION,
        [GRAPHICS_SETTING_SHADOWS                        ] = SI_GRAPHICS_OPTIONS_VIDEO_SHADOWS,
        [GRAPHICS_SETTING_SHOW_ADDITIONAL_ALLY_EFFECTS   ] = SI_GRAPHICS_OPTIONS_VIDEO_SHOW_ADDITIONAL_ALLY_EFFECTS,
        [GRAPHICS_SETTING_SUB_SAMPLING                   ] = SI_GRAPHICS_OPTIONS_VIDEO_SUB_SAMPLING,
        [GRAPHICS_SETTING_VIEW_DISTANCE                  ] = SI_GRAPHICS_OPTIONS_VIDEO_VIEW_DISTANCE,
        [GRAPHICS_SETTING_VSYNC                          ] = SI_GRAPHICS_OPTIONS_VIDEO_VSYNC,
    },

    [SETTING_TYPE_IN_WORLD] = {
        [IN_WORLD_UI_SETTING_DEFAULT_SOUL_GEM            ] = SI_GAMEPLAY_OPTIONS_DEFAULT_SOUL_GEM,
        [IN_WORLD_UI_SETTING_FOOT_INVERSE_KINEMATICS     ] = SI_INTERFACE_OPTIONS_FOOT_INVERSE_KINEMATICS,
        [IN_WORLD_UI_SETTING_GLOW_THICKNESS              ] = SI_INTERFACE_OPTIONS_GLOWS_THICKNESS,
        [IN_WORLD_UI_SETTING_HIDE_MOUNT_INVENTORY_UPGRADE] = SI_INTERFACE_OPTIONS_HIDE_MOUNT_INVENTORY_UPGRADE,
        [IN_WORLD_UI_SETTING_HIDE_MOUNT_SPEED_UPGRADE    ] = SI_INTERFACE_OPTIONS_HIDE_MOUNT_SPEED_UPGRADE,
        [IN_WORLD_UI_SETTING_HIDE_MOUNT_STAMINA_UPGRADE  ] = SI_INTERFACE_OPTIONS_HIDE_MOUNT_STAMINA_UPGRADE,
        [IN_WORLD_UI_SETTING_HIDE_POLYMORPH_HELM         ] = SI_INTERFACE_OPTIONS_HIDE_POLYMORPH_HELM,
        [IN_WORLD_UI_SETTING_INTERACTABLE_GLOW_ENABLED   ] = SI_INTERFACE_OPTIONS_INTERACTABLE_GLOWS_ENABLED,
        [IN_WORLD_UI_SETTING_INTERACTABLE_GLOW_INTENSITY ] = SI_INTERFACE_OPTIONS_INTERACTABLE_GLOWS_INTENSITY,
        [IN_WORLD_UI_SETTING_TARGET_GLOW_ENABLED         ] = SI_INTERFACE_OPTIONS_TARGET_GLOWS_ENABLED,
        [IN_WORLD_UI_SETTING_TARGET_GLOW_INTENSITY       ] = SI_INTERFACE_OPTIONS_TARGET_GLOWS_INTENSITY,
    },

    [SETTING_TYPE_LANGUAGE] = {
        [LANGUAGE_SETTING_USE_PROFANITY_FILTER] = SI_INTERFACE_OPTIONS_LANGUAGE_USE_PROFANITY_FILTER,
    },

    [SETTING_TYPE_LOOT] = {
        [LOOT_SETTING_AOE_LOOT             ] = SI_INTERFACE_OPTIONS_LOOT_USE_AOELOOT,
        [LOOT_SETTING_AUTO_ADD_TO_CRAFT_BAG] = SI_INTERFACE_OPTIONS_LOOT_AUTO_ADD_TO_CRAFT_BAG,
        [LOOT_SETTING_AUTO_LOOT            ] = SI_INTERFACE_OPTIONS_LOOT_USE_AUTOLOOT,
        [LOOT_SETTING_AUTO_LOOT_STOLEN     ] = SI_INTERFACE_OPTIONS_LOOT_USE_AUTOLOOT_STOLEN,
        [LOOT_SETTING_LOOT_HISTORY         ] = SI_INTERFACE_OPTIONS_LOOT_TOGGLE_LOOT_HISTORY,
    },

    [SETTING_TYPE_NAMEPLATES] = {
        [NAMEPLATE_TYPE_ALLIANCE_INDICATORS                 ] = SI_INTERFACE_OPTIONS_NAMEPLATES_ALLIANCE_INDICATORS,
        [NAMEPLATE_TYPE_ALL_HEALTHBARS                      ] = SI_INTERFACE_OPTIONS_HEALTHBARS_ALL,
        [NAMEPLATE_TYPE_ALL_NAMEPLATES                      ] = SI_INTERFACE_OPTIONS_NAMEPLATES_ALL,
        [NAMEPLATE_TYPE_ENEMY_NPC_HEALTHBARS                ] = SI_INTERFACE_OPTIONS_HEALTHBARS_ENEMY_NPC,
        [NAMEPLATE_TYPE_ENEMY_NPC_HEALTHBARS_HIGHLIGHT      ] = SI_INTERFACE_OPTIONS_HEALTHBARS_HIGHLIGHT_ENEMY_NPC,
        [NAMEPLATE_TYPE_ENEMY_NPC_NAMEPLATES                ] = SI_INTERFACE_OPTIONS_NAMEPLATES_ENEMY_NPC,
        [NAMEPLATE_TYPE_ENEMY_NPC_NAMEPLATES_HIGHLIGHT      ] = SI_INTERFACE_OPTIONS_NAMEPLATES_HIGHLIGHT_ENEMY_NPC,
        [NAMEPLATE_TYPE_ENEMY_PLAYER_HEALTHBARS             ] = SI_INTERFACE_OPTIONS_HEALTHBARS_ENEMY_PLAYER,
        [NAMEPLATE_TYPE_ENEMY_PLAYER_HEALTHBARS_HIGHLIGHT   ] = SI_INTERFACE_OPTIONS_HEALTHBARS_HIGHLIGHT_ENEMY_PLAYER,
        [NAMEPLATE_TYPE_ENEMY_PLAYER_NAMEPLATES             ] = SI_INTERFACE_OPTIONS_NAMEPLATES_ENEMY_PLAYER,
        [NAMEPLATE_TYPE_ENEMY_PLAYER_NAMEPLATES_HIGHLIGHT   ] = SI_INTERFACE_OPTIONS_NAMEPLATES_HIGHLIGHT_ENEMY_PLAYER,
        [NAMEPLATE_TYPE_FOLLOWER_INDICATORS                 ] = SI_INTERFACE_OPTIONS_NAMEPLATES_FOLLOWER_INDICATORS,
        [NAMEPLATE_TYPE_FRIENDLY_NPC_HEALTHBARS             ] = SI_INTERFACE_OPTIONS_HEALTHBARS_FRIENDLY_NPC,
        [NAMEPLATE_TYPE_FRIENDLY_NPC_HEALTHBARS_HIGHLIGHT   ] = SI_INTERFACE_OPTIONS_HEALTHBARS_HIGHLIGHT_FRIENDLY_NPC,
        [NAMEPLATE_TYPE_FRIENDLY_NPC_NAMEPLATES             ] = SI_INTERFACE_OPTIONS_NAMEPLATES_FRIENDLY_NPC,
        [NAMEPLATE_TYPE_FRIENDLY_NPC_NAMEPLATES_HIGHLIGHT   ] = SI_INTERFACE_OPTIONS_NAMEPLATES_HIGHLIGHT_FRIENDLY_NPC,
        [NAMEPLATE_TYPE_FRIENDLY_PLAYER_HEALTHBARS          ] = SI_INTERFACE_OPTIONS_HEALTHBARS_FRIENDLY_NPC,
        [NAMEPLATE_TYPE_FRIENDLY_PLAYER_HEALTHBARS_HIGHLIGHT] = SI_INTERFACE_OPTIONS_HEALTHBARS_HIGHLIGHT_FRIENDLY_NPC,
        [NAMEPLATE_TYPE_FRIENDLY_PLAYER_NAMEPLATES          ] = SI_INTERFACE_OPTIONS_NAMEPLATES_FRIENDLY_PLAYER,
        [NAMEPLATE_TYPE_FRIENDLY_PLAYER_NAMEPLATES_HIGHLIGHT] = SI_INTERFACE_OPTIONS_NAMEPLATES_HIGHLIGHT_FRIENDLY_PLAYER,
        [NAMEPLATE_TYPE_GROUP_INDICATORS                    ] = SI_INTERFACE_OPTIONS_NAMEPLATES_GROUP_INDICATORS,
        [NAMEPLATE_TYPE_GROUP_MEMBER_HEALTHBARS             ] = SI_INTERFACE_OPTIONS_HEALTHBARS_GROUP_MEMBER,
        [NAMEPLATE_TYPE_GROUP_MEMBER_HEALTHBARS_HIGHLIGHT   ] = SI_INTERFACE_OPTIONS_HEALTHBARS_HIGHLIGHT_GROUP_MEMBER,
        [NAMEPLATE_TYPE_GROUP_MEMBER_NAMEPLATES             ] = SI_INTERFACE_OPTIONS_NAMEPLATES_GROUP_MEMBER,
        [NAMEPLATE_TYPE_GROUP_MEMBER_NAMEPLATES_HIGHLIGHT   ] = SI_INTERFACE_OPTIONS_NAMEPLATES_HIGHLIGHT_GROUP_MEMBER,
        [NAMEPLATE_TYPE_HEALTHBAR_ALIGNMENT                 ] = SI_INTERFACE_OPTIONS_HEALTHBAR_ALIGNMENT,
        [NAMEPLATE_TYPE_HEALTHBAR_CHASE_BAR                 ] = SI_INTERFACE_OPTIONS_HEALTHBAR_CHASE_BAR,
        [NAMEPLATE_TYPE_HEALTHBAR_FRAME_BORDER              ] = SI_INTERFACE_OPTIONS_HEALTHBAR_FRAME_BORDER,
        [NAMEPLATE_TYPE_NEUTRAL_NPC_HEALTHBARS              ] = SI_INTERFACE_OPTIONS_HEALTHBARS_NEUTRAL_NPC,
        [NAMEPLATE_TYPE_NEUTRAL_NPC_HEALTHBARS_HIGHLIGHT    ] = SI_INTERFACE_OPTIONS_HEALTHBARS_HIGHLIGHT_NEUTRAL_NPC,
        [NAMEPLATE_TYPE_NEUTRAL_NPC_NAMEPLATES              ] = SI_INTERFACE_OPTIONS_NAMEPLATES_NEUTRAL_NPC,
        [NAMEPLATE_TYPE_NEUTRAL_NPC_NAMEPLATES_HIGHLIGHT    ] = SI_INTERFACE_OPTIONS_NAMEPLATES_HIGHLIGHT_NEUTRAL_NPC,
        [NAMEPLATE_TYPE_PLAYER_HEALTHBAR                    ] = SI_INTERFACE_OPTIONS_HEALTHBARS_PLAYER,
        [NAMEPLATE_TYPE_PLAYER_HEALTHBAR_HIGHLIGHT          ] = SI_INTERFACE_OPTIONS_HEALTHBARS_HIGHLIGHT_PLAYER,
        [NAMEPLATE_TYPE_PLAYER_NAMEPLATE                    ] = SI_INTERFACE_OPTIONS_NAMEPLATES_PLAYER,
        [NAMEPLATE_TYPE_PLAYER_NAMEPLATE_HIGHLIGHT          ] = SI_INTERFACE_OPTIONS_NAMEPLATES_HIGHLIGHT_PLAYER,
        [NAMEPLATE_TYPE_RESURRECT_INDICATORS                ] = SI_INTERFACE_OPTIONS_NAMEPLATES_RESURRECT_INDICATORS,
        [NAMEPLATE_TYPE_SHOW_PLAYER_GUILDS                  ] = SI_INTERFACE_OPTIONS_NAMEPLATES_SHOW_PLAYER_GUILDS,
        [NAMEPLATE_TYPE_SHOW_PLAYER_TITLES                  ] = SI_INTERFACE_OPTIONS_NAMEPLATES_SHOW_PLAYER_TITLES,
    },
    -- [SETTING_TYPE_SUBTITLES] = {
        -- [SUBTITLE_SETTING_ENABLED] = SI_INTERFACE_OPTIONS_TOOLTIPS_SUBTITLES_ENABLED
    -- },

    [SETTING_TYPE_TUTORIAL] = {
        [TUTORIAL_ENABLED_SETTING_ID           ] = SI_INTERFACE_OPTIONS_TOOLTIPS_TUTORIAL_ENABLED,
        [OPTIONS_CUSTOM_SETTING_RESET_TUTORIALS] = SI_INTERFACE_OPTIONS_RESET_TUTORIALS
    },

    [SETTING_TYPE_UI] = {
        [UI_SETTING_AUTO_DECLINE_DUEL_INVITES     ] = SI_SOCIAL_OPTIONS_AUTO_DECLINE_DUEL_INVITES,
        [UI_SETTING_COMPASS_ACTIVE_QUESTS         ] = SI_INTERFACE_OPTIONS_COMPASS_ACTIVE_QUESTS,
        [UI_SETTING_COMPASS_QUEST_GIVERS          ] = SI_INTERFACE_OPTIONS_COMPASS_QUEST_GIVERS,
        [UI_SETTING_CUSTOM_SCALE                  ] = SI_VIDEO_OPTIONS_UI_CUSTOM_SCALE,
        [UI_SETTING_FRAMERATE_LATENCY_LOCK        ] = SI_INTERFACE_OPTIONS_SHOW_FRAMERATE,
        [UI_SETTING_GAMEPAD_CHAT_HUD_ENABLED      ] = SI_SOCIAL_OPTIONS_GAMEPAD_CHAT_HUD_ENABLED,
        [UI_SETTING_PRIMARY_PLAYER_NAME_GAMEPAD   ] = SI_GAMEPAD_INTERFACE_OPTIONS_PRIMARY_PLAYER_NAME,
        [UI_SETTING_PRIMARY_PLAYER_NAME_KEYBOARD  ] = SI_INTERFACE_OPTIONS_PRIMARY_PLAYER_NAME_KEYBOARD,
        [UI_SETTING_RESOURCE_NUMBERS              ] = SI_INTERFACE_OPTIONS_RESOURCE_NUMBERS,
        [UI_SETTING_RETURN_CURSOR_ON_CHAT_FOCUS   ] = SI_INTERFACE_OPTIONS_RETURN_CURSOR_ON_CHAT_FOCUS,
        [UI_SETTING_SHOW_ACTION_BAR               ] = SI_INTERFACE_OPTIONS_ACTION_BAR,
        [UI_SETTING_SHOW_ARMOR_INDICATOR          ] = SI_ARMOR_INDICATOR,
        [UI_SETTING_SHOW_AVA_NOTIFICATIONS        ] = SI_SOCIAL_OPTIONS_SHOW_AVA_NOTIFICATIONS,
        [UI_SETTING_SHOW_FRAMERATE                ] = SI_INTERFACE_OPTIONS_SHOW_FRAMERATE,
        [UI_SETTING_SHOW_LATENCY                  ] = SI_INTERFACE_OPTIONS_SHOW_LATENCY,
        [UI_SETTING_SHOW_LEADERBOARD_NOTIFICATIONS] = SI_SOCIAL_OPTIONS_SHOW_LEADERBOARD_NOTIFICATIONS,
        [UI_SETTING_SHOW_QUEST_BESTOWER_INDICATORS] = SI_INTERFACE_OPTIONS_SHOW_QUEST_BESTOWERS,
        [UI_SETTING_SHOW_QUEST_TRACKER            ] = SI_INTERFACE_OPTIONS_SHOW_QUEST_TRACKER,
        [UI_SETTING_SHOW_RAID_LIVES               ] = SI_INTERFACE_OPTIONS_SHOW_RAID_LIVES,
        [UI_SETTING_SHOW_RESOURCE_BARS            ] = SI_INTERFACE_OPTIONS_RESOURCE_BARS,
        [UI_SETTING_SHOW_WEAPON_INDICATOR         ] = SI_WEAPON_INDICATOR,
        [UI_SETTING_SOCIAL_LIST_HIDE_OFFLINE      ] = SI_SOCIAL_LIST_SHOW_OFFLINE,
        [UI_SETTING_ULTIMATE_NUMBER               ] = SI_INTERFACE_OPTIONS_ULTIMATE_NUMBER,
        [UI_SETTING_USE_CUSTOM_SCALE              ] = SI_VIDEO_OPTIONS_UI_USE_CUSTOM_SCALE,
    },
}

AccountSettings.SettingTooltipStrings = {
    [SETTING_TYPE_ACTIVE_COMBAT_TIP] = {
        [0] = SI_INTERFACE_OPTIONS_ACT_SETTING_LABEL_TOOLTIP
    },

    [SETTING_TYPE_AUDIO] = {
        [AUDIO_SETTING_AMBIENT_VOLUME]    = SI_AUDIO_OPTIONS_AMBIENT_VOLUME_TOOLTIP,
        [AUDIO_SETTING_AUDIO_VOLUME]      = SI_AUDIO_OPTIONS_MASTER_VOLUME_TOOLTIP,
        [AUDIO_SETTING_BACKGROUND_AUDIO]  = SI_AUDIO_OPTIONS_BACKGROUND_AUDIO_TOOLTIP,
        [AUDIO_SETTING_FOOTSTEPS_VOLUME]  = SI_AUDIO_OPTIONS_FOOTSTEPS_VOLUME_TOOLTIP,
        [AUDIO_SETTING_MUSIC_ENABLED]     = SI_AUDIO_OPTIONS_MUSIC_ENABLED_TOOLTIP,
        [AUDIO_SETTING_MUSIC_VOLUME]      = SI_AUDIO_OPTIONS_MUSIC_VOLUME_TOOLTIP,
        [AUDIO_SETTING_SFX_ENABLED]       = SI_AUDIO_OPTIONS_SOUND_ENABLED_TOOLTIP,
        [AUDIO_SETTING_SFX_VOLUME]        = SI_AUDIO_OPTIONS_SFX_VOLUME_TOOLTIP,
        [AUDIO_SETTING_UI_VOLUME]         = SI_AUDIO_OPTIONS_UI_VOLUME_TOOLTIP,
        [AUDIO_SETTING_VOICE_CHAT_VOLUME] = SI_GAMEPAD_AUDIO_OPTIONS_VOICECHAT_VOLUME_TOOLTIP,
        [AUDIO_SETTING_VO_VOLUME]         = SI_AUDIO_OPTIONS_VO_VOLUME_TOOLTIP,
    },

    [SETTING_TYPE_BUFFS] = {
        [BUFFS_SETTING_ALL_ENABLED                           ]  = SI_BUFFS_OPTIONS_ALL_ENABLED_TOOLTIP,
        [BUFFS_SETTING_BUFFS_ENABLED                         ]  = SI_BUFFS_OPTIONS_BUFFS_ENABLED_TOOLTIP,
        [BUFFS_SETTING_BUFFS_ENABLED_FOR_SELF                ]  = SI_BUFFS_OPTIONS_BUFFS_ENABLED_FOR_SELF_TOOLTIP,
        [BUFFS_SETTING_BUFFS_ENABLED_FOR_TARGET              ]  = SI_BUFFS_OPTIONS_BUFFS_ENABLED_FOR_TARGET_TOOLTIP,
        [BUFFS_SETTING_DEBUFFS_ENABLED                       ]  = SI_BUFFS_OPTIONS_DEBUFFS_ENABLED_TOOLTIP,
        [BUFFS_SETTING_DEBUFFS_ENABLED_FOR_SELF              ]  = SI_BUFFS_OPTIONS_DEBUFFS_ENABLED_FOR_SELF_TOOLTIP,
        [BUFFS_SETTING_DEBUFFS_ENABLED_FOR_TARGET            ]  = SI_BUFFS_OPTIONS_DEBUFFS_ENABLED_FOR_TARGET_TOOLTIP,
        [BUFFS_SETTING_DEBUFFS_ENABLED_FOR_TARGET_FROM_OTHERS]  = SI_BUFFS_OPTIONS_DEBUFFS_ENABLED_FOR_TARGET_FROM_OTHERS_TOOLTIP,
        [BUFFS_SETTING_LONG_EFFECTS                          ]  = SI_BUFFS_OPTIONS_LONG_EFFECTS_TOOLTIP,
        [BUFFS_SETTING_PERMANENT_EFFECTS                     ]  = SI_BUFFS_OPTIONS_PERMANENT_EFFECTS_TOOLTIP,
    },

    [SETTING_TYPE_CAMERA] = {
        [CAMERA_SETTING_ASSASSINATION_CAMERA                       ] = SI_INTERFACE_OPTIONS_CAMERA_ASSASSINATION_CAMERA_TOOLTIP,
        [CAMERA_SETTING_FIRST_PERSON_FIELD_OF_VIEW                 ] = SI_INTERFACE_OPTIONS_CAMERA_FIRST_PERSON_FOV_TOOLTIP,
        [CAMERA_SETTING_FIRST_PERSON_HEAD_BOB                      ] = SI_INTERFACE_OPTIONS_CAMERA_FIRST_PERSON_BOB_TOOLTIP,
        [CAMERA_SETTING_FOV_CHANGES_ALLOWED                        ] = SI_INTERFACE_OPTIONS_CAMERA_FOV_CHANGES_TOOLTIP,
        [CAMERA_SETTING_INVERT_Y                                   ] = SI_INTERFACE_OPTIONS_CAMERA_INVERT_Y_TOOLTIP,
        [CAMERA_SETTING_SCREEN_SHAKE                               ] = SI_INTERFACE_OPTIONS_CAMERA_SCREEN_SHAKE_TOOLTIP,
        [CAMERA_SETTING_SENSITIVITY_FIRST_PERSON                   ] = SI_INTERFACE_OPTIONS_CAMERA_SENSITIVITY_FIRST_PERSON_TOOLTIP,
        [CAMERA_SETTING_SENSITIVITY_THIRD_PERSON                   ] = SI_INTERFACE_OPTIONS_CAMERA_SENSITIVITY_THIRD_PERSON_TOOLTIP,
        [CAMERA_SETTING_SMOOTHING                                  ] = SI_INTERFACE_OPTIONS_CAMERA_SMOOTHING_TOOLTIP,
        [CAMERA_SETTING_THIRD_PERSON_FIELD_OF_VIEW                 ] = SI_INTERFACE_OPTIONS_CAMERA_THIRD_PERSON_FOV_TOOLTIP,
        [CAMERA_SETTING_THIRD_PERSON_HORIZONTAL_OFFSET             ] = SI_INTERFACE_OPTIONS_CAMERA_THIRD_PERSON_HORIZONTAL_OFFSET_TOOLTIP,
        [CAMERA_SETTING_THIRD_PERSON_HORIZONTAL_POSITION_MULTIPLIER] = SI_INTERFACE_OPTIONS_CAMERA_THIRD_PERSON_HORIZONTAL_POSITION_MULTIPLIER_TOOLTIP,
        [CAMERA_SETTING_THIRD_PERSON_SIEGE_WEAPONRY                ] = SI_INTERFACE_OPTIONS_CAMERA_THIRD_PERSON_SIEGE_WEAPONRY_TOOLTIP,
        [CAMERA_SETTING_THIRD_PERSON_VERTICAL_OFFSET               ] = SI_INTERFACE_OPTIONS_CAMERA_THIRD_PERSON_VERTICAL_OFFSET_TOOLTIP,
    },

    [SETTING_TYPE_CHAT_BUBBLE] = {
        [CHAT_BUBBLE_SETTING_ENABLED                   ] = SI_INTERFACE_OPTIONS_CHAT_BUBBLES_TOOLTIP,
        [CHAT_BUBBLE_SETTING_ENABLED_FOR_LOCAL_PLAYER  ] = SI_INTERFACE_OPTIONS_CHAT_BUBBLES_SELF_TOOLTIP,
        [CHAT_BUBBLE_SETTING_ENABLED_ONLY_FROM_CONTACTS] = SI_INTERFACE_OPTIONS_CHAT_BUBBLES_ONLY_KNOWN_TOOLTIP,
        [CHAT_BUBBLE_SETTING_SPEED_MODIFIER            ] = SI_INTERFACE_OPTIONS_CHAT_BUBBLES_FADE_RATE_TOOLTIP,
    },

    [SETTING_TYPE_COMBAT] = {
        [COMBAT_SETTING_CLAMP_GROUND_TARGET_ENABLED        ] = SI_INTERFACE_OPTIONS_COMBAT_CLAMP_GROUND_TARGET_ENABLED_TOOLTIP,
        [COMBAT_SETTING_MONSTER_TELLS_COLOR_SWAP_ENABLED   ] = SI_INTERFACE_OPTIONS_COMBAT_MONSTER_TELLS_COLOR_SWAP_ENABLED_TOOLTIP,
        [COMBAT_SETTING_MONSTER_TELLS_ENABLED              ] = SI_INTERFACE_OPTIONS_COMBAT_MONSTER_TELLS_ENABLE_TOOLTIP,
        [COMBAT_SETTING_MONSTER_TELLS_ENEMY_BRIGHTNESS     ] = SI_INTERFACE_OPTIONS_COMBAT_MONSTER_TELLS_ENEMY_BRIGHTNESS_TOOLTIP,
        [COMBAT_SETTING_MONSTER_TELLS_ENEMY_COLOR          ] = SI_INTERFACE_OPTIONS_COMBAT_MONSTER_TELLS_ENEMY_COLOR_TOOLTIP,
        [COMBAT_SETTING_MONSTER_TELLS_FRIENDLY_BRIGHTNESS  ] = SI_INTERFACE_OPTIONS_COMBAT_MONSTER_TELLS_FRIENDLY_BRIGHTNESS_TOOLTIP,
        [COMBAT_SETTING_MONSTER_TELLS_FRIENDLY_COLOR       ] = SI_INTERFACE_OPTIONS_COMBAT_MONSTER_TELLS_FRIENDLY_COLOR_TOOLTIP,
        [COMBAT_SETTING_PREVENT_ATTACKING_INNOCENTS        ] = SI_INTERFACE_OPTIONS_COMBAT_PREVENT_ATTACKING_INNOCENTS_TOOLTIP,
        [COMBAT_SETTING_QUICK_CAST_GROUND_ABILITIES        ] = SI_INTERFACE_OPTIONS_COMBAT_QUICK_CAST_GROUND_ABILITIES_TOOLTIP,
        [COMBAT_SETTING_ROLL_DODGE_DOUBLE_TAP              ] = SI_INTERFACE_OPTIONS_COMBAT_ROLL_DODGE_ENABLED_TOOLTIP,
        [COMBAT_SETTING_ROLL_DODGE_WINDOW                  ] = SI_INTERFACE_OPTIONS_COMBAT_ROLL_DODGE_WINDOW_TOOLTIP,
        [COMBAT_SETTING_SCROLLING_COMBAT_TEXT_ENABLED      ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_INCOMING_DAMAGE_ENABLED        ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_DAMAGE_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_INCOMING_DOT_ENABLED           ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_DOT_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_INCOMING_ENABLED               ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_INCOMING_HEALING_ENABLED       ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_HEALING_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_INCOMING_HOT_ENABLED           ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_HOT_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_INCOMING_PET_DAMAGE_ENABLED    ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_PET_DAMAGE_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_INCOMING_PET_DOT_ENABLED       ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_PET_DOT_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_INCOMING_POINT_GAINS_ENABLED   ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_POINT_GAINS_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_INCOMING_STATUS_EFFECTS_ENABLED] = SI_INTERFACE_OPTIONS_COMBAT_SCT_INCOMING_STATUS_EFFECTS_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_OUTGOING_DAMAGE_ENABLED        ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_DAMAGE_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_OUTGOING_DOT_ENABLED           ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_DOT_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_OUTGOING_ENABLED               ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_OUTGOING_HEALING_ENABLED       ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_HEALING_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_OUTGOING_HOT_ENABLED           ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_HOT_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_OUTGOING_PET_DAMAGE_ENABLED    ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_PET_DAMAGE_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_OUTGOING_PET_DOT_ENABLED       ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_PET_DOT_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_OUTGOING_PET_HEALING_ENABLED   ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_PET_HEALING_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_OUTGOING_PET_HOT_ENABLED       ] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_PET_HOT_ENABLED_TOOLTIP,
        [COMBAT_SETTING_SCT_OUTGOING_STATUS_EFFECTS_ENABLED] = SI_INTERFACE_OPTIONS_COMBAT_SCT_OUTGOING_STATUS_EFFECTS_ENABLED_TOOLTIP,
        [COMBAT_SETTING_ENCOUNTER_LOG_APPEAR_ANONYMOUS     ] = SI_INTERFACE_OPTIONS_COMBAT_ENCOUNTER_LOG_APPEAR_ANONYMOUS_TOOLTIP
    },

    [SETTING_TYPE_GAMEPAD] = {
        [GAMEPAD_SETTING_CAMERA_SENSITIVITY] = SI_GAMEPAD_OPTIONS_CAMERA_SENSITIVITY_TOOLTIP,
        [GAMEPAD_SETTING_GAMEPAD_TEMPLATE  ] = SI_GAMEPAD_OPTIONS_TEMPLATES_TOOLTIP,
        [GAMEPAD_SETTING_INVERT_Y          ] = SI_GAMEPAD_OPTIONS_INVERT_Y_TOOLTIP,
        [GAMEPAD_SETTING_VIBRATION         ] = SI_GAMEPAD_OPTIONS_CAMERA_VIBRATION_TOOLTIP,
    },

    [SETTING_TYPE_GRAPHICS] = {
        [GRAPHICS_SETTING_AMBIENT_OCCLUSION_TYPE         ] = SI_GRAPHICS_OPTIONS_VIDEO_AMBIENT_OCCLUSION_TYPE_TOOLTIP,
        [GRAPHICS_SETTING_ANTI_ALIASING                  ] = SI_GRAPHICS_OPTIONS_VIDEO_ANTI_ALIASING_TOOLTIP,
        [GRAPHICS_SETTING_BLOOM                          ] = SI_GRAPHICS_OPTIONS_VIDEO_BLOOM_TOOLTIP,
        [GRAPHICS_SETTING_CLUTTER_2D                     ] = SI_GRAPHICS_OPTIONS_VIDEO_CLUTTER_2D_TOOLTIP,
        [GRAPHICS_SETTING_CONSOLE_ENHANCED_RENDER_QUALITY] = SI_GRAPHICS_OPTIONS_CONSOLE_ENHANCED_RENDER_QUALITY_TOOLTIP,
        [GRAPHICS_SETTING_DEPTH_OF_FIELD                 ] = SI_GRAPHICS_OPTIONS_VIDEO_DEPTH_OF_FIELD_TOOLTIP,
        [GRAPHICS_SETTING_DISTORTION                     ] = SI_GRAPHICS_OPTIONS_VIDEO_DISTORTION_TOOLTIP,
        [GRAPHICS_SETTING_FULLSCREEN                     ] = SI_GRAPHICS_OPTIONS_VIDEO_DISPLAY_MODE_TOOLTIP,
        [GRAPHICS_SETTING_GAMMA_ADJUSTMENT               ] = SI_GRAPHICS_OPTIONS_VIDEO_GAMMA_ADJUSTMENT_TOOLTIP,
        [GRAPHICS_SETTING_GOD_RAYS                       ] = SI_GRAPHICS_OPTIONS_VIDEO_GOD_RAYS_TOOLTIP,
        [GRAPHICS_SETTING_HDR_BRIGHTNESS                 ] = SI_GRAPHICS_OPTIONS_VIDEO_HDR_BRIGHTNESS_TOOLTIP,
        [GRAPHICS_SETTING_MIP_LOAD_SKIP_LEVELS           ] = SI_GRAPHICS_OPTIONS_VIDEO_TEXTURE_RES_TOOLTIP,
        [GRAPHICS_SETTING_PFX_GLOBAL_MAXIMUM             ] = SI_GRAPHICS_OPTIONS_VIDEO_MAXIMUM_PARTICLE_SYSTEMS_TOOLTIP,
        [GRAPHICS_SETTING_PFX_SUPPRESS_DISTANCE          ] = SI_GRAPHICS_OPTIONS_VIDEO_PARTICLE_SUPPRESSION_DISTANCE_TOOLTIP,
        [GRAPHICS_SETTING_PRESETS                        ] = SI_GRAPHICS_OPTIONS_VIDEO_PRESETS_TOOLTIP,
        [GRAPHICS_SETTING_REFLECTION_QUALITY             ] = SI_GRAPHICS_OPTIONS_VIDEO_REFLECTION_QUALITY_TOOLTIP,
        [GRAPHICS_SETTING_RESOLUTION                     ] = SI_GRAPHICS_OPTIONS_VIDEO_RESOLUTION_TOOLTIP,
        [GRAPHICS_SETTING_SHADOWS                        ] = SI_GRAPHICS_OPTIONS_VIDEO_SHADOWS_TOOLTIP,
        [GRAPHICS_SETTING_SHOW_ADDITIONAL_ALLY_EFFECTS   ] = SI_GRAPHICS_OPTIONS_VIDEO_SHOW_ADDITIONAL_ALLY_EFFECTS_TOOLTIP,
        [GRAPHICS_SETTING_SUB_SAMPLING                   ] = SI_GRAPHICS_OPTIONS_VIDEO_SUB_SAMPLING_TOOLTIP,
        [GRAPHICS_SETTING_VIEW_DISTANCE                  ] = SI_GRAPHICS_OPTIONS_VIDEO_VIEW_DISTANCE_TOOLTIP,
        [GRAPHICS_SETTING_VSYNC                          ] = SI_GRAPHICS_OPTIONS_VIDEO_VSYNC_TOOLTIP,
    },

    [SETTING_TYPE_IN_WORLD] = {
        [IN_WORLD_UI_SETTING_DEFAULT_SOUL_GEM            ] = SI_GAMEPLAY_OPTIONS_DEFAULT_SOUL_GEM_TOOLTIP,
        [IN_WORLD_UI_SETTING_FOOT_INVERSE_KINEMATICS     ] = SI_INTERFACE_OPTIONS_FOOT_INVERSE_KINEMATICS_TOOLTIP,
        [IN_WORLD_UI_SETTING_GLOW_THICKNESS              ] = SI_INTERFACE_OPTIONS_GLOWS_THICKNESS_TOOLTIP,
        [IN_WORLD_UI_SETTING_HIDE_MOUNT_INVENTORY_UPGRADE] = SI_INTERFACE_OPTIONS_HIDE_MOUNT_INVENTORY_UPGRADE_TOOLTIP,
        [IN_WORLD_UI_SETTING_HIDE_MOUNT_SPEED_UPGRADE    ] = SI_INTERFACE_OPTIONS_HIDE_MOUNT_SPEED_UPGRADE_TOOLTIP,
        [IN_WORLD_UI_SETTING_HIDE_MOUNT_STAMINA_UPGRADE  ] = SI_INTERFACE_OPTIONS_HIDE_MOUNT_STAMINA_UPGRADE_TOOLTIP,
        [IN_WORLD_UI_SETTING_HIDE_POLYMORPH_HELM         ] = SI_INTERFACE_OPTIONS_HIDE_POLYMORPH_HELM_TOOLTIP,
        [IN_WORLD_UI_SETTING_INTERACTABLE_GLOW_ENABLED   ] = SI_INTERFACE_OPTIONS_INTERACTABLE_GLOWS_ENABLED_TOOLTIP,
        [IN_WORLD_UI_SETTING_INTERACTABLE_GLOW_INTENSITY ] = SI_INTERFACE_OPTIONS_INTERACTABLE_GLOWS_INTENSITY_TOOLTIP,
        [IN_WORLD_UI_SETTING_TARGET_GLOW_ENABLED         ] = SI_INTERFACE_OPTIONS_TARGET_GLOWS_ENABLED_TOOLTIP,
        [IN_WORLD_UI_SETTING_TARGET_GLOW_INTENSITY       ] = SI_INTERFACE_OPTIONS_TARGET_GLOWS_INTENSITY_TOOLTIP,
    },

    [SETTING_TYPE_LANGUAGE] = {
        [LANGUAGE_SETTING_USE_PROFANITY_FILTER] = SI_INTERFACE_OPTIONS_LANGUAGE_USE_PROFANITY_FILTER_TOOLTIP,
    },

    [SETTING_TYPE_LOOT] = {
        [LOOT_SETTING_AOE_LOOT             ] = SI_INTERFACE_OPTIONS_LOOT_USE_AOELOOT_TOOLTIP,
        [LOOT_SETTING_AUTO_ADD_TO_CRAFT_BAG] = SI_INTERFACE_OPTIONS_LOOT_AUTO_ADD_TO_CRAFT_BAG_TOOLTIP,
        [LOOT_SETTING_AUTO_LOOT            ] = SI_INTERFACE_OPTIONS_LOOT_USE_AUTOLOOT_TOOLTIP,
        [LOOT_SETTING_AUTO_LOOT_STOLEN     ] = SI_INTERFACE_OPTIONS_LOOT_USE_AUTOLOOT_STOLEN_TOOLTIP,
        [LOOT_SETTING_LOOT_HISTORY         ] = SI_INTERFACE_OPTIONS_LOOT_TOGGLE_LOOT_HISTORY_TOOLTIP,
    },

    [SETTING_TYPE_NAMEPLATES] = {
        [NAMEPLATE_TYPE_ALLIANCE_INDICATORS                 ] = SI_INTERFACE_OPTIONS_NAMEPLATES_ALLIANCE_INDICATORS_TOOLTIP,
        [NAMEPLATE_TYPE_ALL_HEALTHBARS                      ] = SI_INTERFACE_OPTIONS_HEALTHBARS_ALL_TOOLTIP,
        [NAMEPLATE_TYPE_ALL_NAMEPLATES                      ] = SI_INTERFACE_OPTIONS_NAMEPLATES_ALL_TOOLTIP,
        [NAMEPLATE_TYPE_ENEMY_NPC_HEALTHBARS                ] = SI_INTERFACE_OPTIONS_HEALTHBARS_ENEMY_NPC_TOOLTIP,
        [NAMEPLATE_TYPE_ENEMY_NPC_HEALTHBARS_HIGHLIGHT      ] = SI_INTERFACE_OPTIONS_HEALTHBARS_HIGHLIGHT_ENEMY_NPC_TOOLTIP,
        [NAMEPLATE_TYPE_ENEMY_NPC_NAMEPLATES                ] = SI_INTERFACE_OPTIONS_NAMEPLATES_ENEMY_NPC_TOOLTIP,
        [NAMEPLATE_TYPE_ENEMY_NPC_NAMEPLATES_HIGHLIGHT      ] = SI_INTERFACE_OPTIONS_NAMEPLATES_HIGHLIGHT_ENEMY_NPC_TOOLTIP,
        [NAMEPLATE_TYPE_ENEMY_PLAYER_HEALTHBARS             ] = SI_INTERFACE_OPTIONS_HEALTHBARS_ENEMY_PLAYER_TOOLTIP,
        [NAMEPLATE_TYPE_ENEMY_PLAYER_HEALTHBARS_HIGHLIGHT   ] = SI_INTERFACE_OPTIONS_HEALTHBARS_HIGHLIGHT_ENEMY_PLAYER_TOOLTIP,
        [NAMEPLATE_TYPE_ENEMY_PLAYER_NAMEPLATES             ] = SI_INTERFACE_OPTIONS_NAMEPLATES_ENEMY_PLAYER_TOOLTIP,
        [NAMEPLATE_TYPE_ENEMY_PLAYER_NAMEPLATES_HIGHLIGHT   ] = SI_INTERFACE_OPTIONS_NAMEPLATES_HIGHLIGHT_ENEMY_PLAYER_TOOLTIP,
        [NAMEPLATE_TYPE_FOLLOWER_INDICATORS                 ] = SI_INTERFACE_OPTIONS_NAMEPLATES_FOLLOWER_INDICATORS_TOOLTIP,
        [NAMEPLATE_TYPE_FRIENDLY_NPC_HEALTHBARS             ] = SI_INTERFACE_OPTIONS_HEALTHBARS_FRIENDLY_NPC_TOOLTIP,
        [NAMEPLATE_TYPE_FRIENDLY_NPC_HEALTHBARS_HIGHLIGHT   ] = SI_INTERFACE_OPTIONS_HEALTHBARS_HIGHLIGHT_FRIENDLY_NPC_TOOLTIP,
        [NAMEPLATE_TYPE_FRIENDLY_NPC_NAMEPLATES             ] = SI_INTERFACE_OPTIONS_NAMEPLATES_FRIENDLY_NPC_TOOLTIP,
        [NAMEPLATE_TYPE_FRIENDLY_NPC_NAMEPLATES_HIGHLIGHT   ] = SI_INTERFACE_OPTIONS_NAMEPLATES_HIGHLIGHT_FRIENDLY_NPC_TOOLTIP,
        [NAMEPLATE_TYPE_FRIENDLY_PLAYER_HEALTHBARS          ] = SI_INTERFACE_OPTIONS_HEALTHBARS_FRIENDLY_NPC_TOOLTIP,
        [NAMEPLATE_TYPE_FRIENDLY_PLAYER_HEALTHBARS_HIGHLIGHT] = SI_INTERFACE_OPTIONS_HEALTHBARS_HIGHLIGHT_FRIENDLY_NPC_TOOLTIP,
        [NAMEPLATE_TYPE_FRIENDLY_PLAYER_NAMEPLATES          ] = SI_INTERFACE_OPTIONS_NAMEPLATES_FRIENDLY_PLAYER_TOOLTIP,
        [NAMEPLATE_TYPE_FRIENDLY_PLAYER_NAMEPLATES_HIGHLIGHT] = SI_INTERFACE_OPTIONS_NAMEPLATES_HIGHLIGHT_FRIENDLY_PLAYER_TOOLTIP,
        [NAMEPLATE_TYPE_GROUP_INDICATORS                    ] = SI_INTERFACE_OPTIONS_NAMEPLATES_GROUP_INDICATORS_TOOLTIP,
        [NAMEPLATE_TYPE_GROUP_MEMBER_HEALTHBARS             ] = SI_INTERFACE_OPTIONS_HEALTHBARS_GROUP_MEMBER_TOOLTIP,
        [NAMEPLATE_TYPE_GROUP_MEMBER_HEALTHBARS_HIGHLIGHT   ] = SI_INTERFACE_OPTIONS_HEALTHBARS_HIGHLIGHT_GROUP_MEMBER_TOOLTIP,
        [NAMEPLATE_TYPE_GROUP_MEMBER_NAMEPLATES             ] = SI_INTERFACE_OPTIONS_NAMEPLATES_GROUP_MEMBER_TOOLTIP,
        [NAMEPLATE_TYPE_GROUP_MEMBER_NAMEPLATES_HIGHLIGHT   ] = SI_INTERFACE_OPTIONS_NAMEPLATES_HIGHLIGHT_GROUP_MEMBER_TOOLTIP,
        [NAMEPLATE_TYPE_HEALTHBAR_ALIGNMENT                 ] = SI_INTERFACE_OPTIONS_HEALTHBAR_ALIGNMENT_TOOLTIP,
        [NAMEPLATE_TYPE_HEALTHBAR_CHASE_BAR                 ] = SI_INTERFACE_OPTIONS_HEALTHBAR_CHASE_BAR_TOOLTIP,
        [NAMEPLATE_TYPE_HEALTHBAR_FRAME_BORDER              ] = SI_INTERFACE_OPTIONS_HEALTHBAR_FRAME_BORDER_TOOLTIP,
        [NAMEPLATE_TYPE_NEUTRAL_NPC_HEALTHBARS              ] = SI_INTERFACE_OPTIONS_HEALTHBARS_NEUTRAL_NPC_TOOLTIP,
        [NAMEPLATE_TYPE_NEUTRAL_NPC_HEALTHBARS_HIGHLIGHT    ] = SI_INTERFACE_OPTIONS_HEALTHBARS_HIGHLIGHT_NEUTRAL_NPC_TOOLTIP,
        [NAMEPLATE_TYPE_NEUTRAL_NPC_NAMEPLATES              ] = SI_INTERFACE_OPTIONS_NAMEPLATES_NEUTRAL_NPC_TOOLTIP,
        [NAMEPLATE_TYPE_NEUTRAL_NPC_NAMEPLATES_HIGHLIGHT    ] = SI_INTERFACE_OPTIONS_NAMEPLATES_HIGHLIGHT_NEUTRAL_NPC_TOOLTIP,
        [NAMEPLATE_TYPE_PLAYER_HEALTHBAR                    ] = SI_INTERFACE_OPTIONS_HEALTHBARS_PLAYER_TOOLTIP,
        [NAMEPLATE_TYPE_PLAYER_HEALTHBAR_HIGHLIGHT          ] = SI_INTERFACE_OPTIONS_HEALTHBARS_HIGHLIGHT_PLAYER_TOOLTIP,
        [NAMEPLATE_TYPE_PLAYER_NAMEPLATE                    ] = SI_INTERFACE_OPTIONS_NAMEPLATES_PLAYER_TOOLTIP,
        [NAMEPLATE_TYPE_PLAYER_NAMEPLATE_HIGHLIGHT          ] = SI_INTERFACE_OPTIONS_NAMEPLATES_HIGHLIGHT_PLAYER_TOOLTIP,
        [NAMEPLATE_TYPE_RESURRECT_INDICATORS                ] = SI_INTERFACE_OPTIONS_NAMEPLATES_RESURRECT_INDICATORS_TOOLTIP,
        [NAMEPLATE_TYPE_SHOW_PLAYER_GUILDS                  ] = SI_INTERFACE_OPTIONS_NAMEPLATES_SHOW_PLAYER_GUILDS_TOOLTIP,
        [NAMEPLATE_TYPE_SHOW_PLAYER_TITLES                  ] = SI_INTERFACE_OPTIONS_NAMEPLATES_SHOW_PLAYER_TITLES_TOOLTIP,
    },
    -- [SETTING_TYPE_SUBTITLES] = {
        -- [SUBTITLE_SETTING_ENABLED] = SI_INTERFACE_OPTIONS_TOOLTIPS_SUBTITLES_ENABLED_TOOLTIP
    -- },

    [SETTING_TYPE_TUTORIAL] = {
        [TUTORIAL_ENABLED_SETTING_ID           ] = SI_INTERFACE_OPTIONS_TOOLTIPS_TUTORIAL_ENABLED_TOOLTIP,
        [OPTIONS_CUSTOM_SETTING_RESET_TUTORIALS] = SI_INTERFACE_OPTIONS_RESET_TUTORIALS_TOOLTIP
    },

    [SETTING_TYPE_UI] = {
        [UI_SETTING_AUTO_DECLINE_DUEL_INVITES     ] = SI_SOCIAL_OPTIONS_AUTO_DECLINE_DUEL_INVITES_TOOLTIP,
        [UI_SETTING_COMPASS_ACTIVE_QUESTS         ] = SI_INTERFACE_OPTIONS_COMPASS_ACTIVE_QUESTS_TOOLTIP,
        [UI_SETTING_COMPASS_QUEST_GIVERS          ] = SI_INTERFACE_OPTIONS_COMPASS_QUEST_GIVERS_TOOLTIP,
        [UI_SETTING_CUSTOM_SCALE                  ] = SI_VIDEO_OPTIONS_UI_CUSTOM_SCALE_TOOLTIP,
        [UI_SETTING_FRAMERATE_LATENCY_LOCK        ] = SI_INTERFACE_OPTIONS_SHOW_FRAMERATE_TOOLTIP,
        [UI_SETTING_GAMEPAD_CHAT_HUD_ENABLED      ] = SI_SOCIAL_OPTIONS_GAMEPAD_CHAT_HUD_ENABLED_TOOLTIP,
        [UI_SETTING_PRIMARY_PLAYER_NAME_GAMEPAD   ] = SI_GAMEPAD_INTERFACE_OPTIONS_PRIMARY_PLAYER_NAME_TOOLTIP,
        [UI_SETTING_PRIMARY_PLAYER_NAME_KEYBOARD  ] = SI_INTERFACE_OPTIONS_PRIMARY_PLAYER_NAME_KEYBOARD_TOOLTIP,
        [UI_SETTING_RESOURCE_NUMBERS              ] = SI_INTERFACE_OPTIONS_RESOURCE_NUMBERS_TOOLTIP,
        [UI_SETTING_RETURN_CURSOR_ON_CHAT_FOCUS   ] = SI_INTERFACE_OPTIONS_RETURN_CURSOR_ON_CHAT_FOCUS_TOOLTIP,
        [UI_SETTING_SHOW_ACTION_BAR               ] = SI_INTERFACE_OPTIONS_ACTION_BAR_TOOLTIP,
        [UI_SETTING_SHOW_ARMOR_INDICATOR          ] = SI_ARMOR_INDICATOR_TOOLTIP,
        [UI_SETTING_SHOW_AVA_NOTIFICATIONS        ] = SI_SOCIAL_OPTIONS_SHOW_AVA_NOTIFICATIONS_TOOLTIP,
        [UI_SETTING_SHOW_FRAMERATE                ] = SI_INTERFACE_OPTIONS_SHOW_FRAMERATE_TOOLTIP,
        [UI_SETTING_SHOW_LATENCY                  ] = SI_INTERFACE_OPTIONS_SHOW_LATENCY_TOOLTIP,
        [UI_SETTING_SHOW_LEADERBOARD_NOTIFICATIONS] = SI_SOCIAL_OPTIONS_SHOW_LEADERBOARD_NOTIFICATIONS_TOOLTIP,
        [UI_SETTING_SHOW_QUEST_BESTOWER_INDICATORS] = SI_INTERFACE_OPTIONS_SHOW_QUEST_BESTOWERS_TOOLTIP,
        [UI_SETTING_SHOW_QUEST_TRACKER            ] = SI_INTERFACE_OPTIONS_SHOW_QUEST_TRACKER_TOOLTIP,
        [UI_SETTING_SHOW_RAID_LIVES               ] = SI_INTERFACE_OPTIONS_SHOW_RAID_LIVES_TOOLTIP,
        [UI_SETTING_SHOW_RESOURCE_BARS            ] = SI_INTERFACE_OPTIONS_RESOURCE_BARS_TOOLTIP,
        [UI_SETTING_SHOW_WEAPON_INDICATOR         ] = SI_WEAPON_INDICATOR_TOOLTIP,
        [UI_SETTING_SOCIAL_LIST_HIDE_OFFLINE      ] = SI_SOCIAL_LIST_SHOW_OFFLINE_TOOLTIP,
        [UI_SETTING_ULTIMATE_NUMBER               ] = SI_INTERFACE_OPTIONS_ULTIMATE_NUMBER_TOOLTIP,
        [UI_SETTING_USE_CUSTOM_SCALE              ] = SI_VIDEO_OPTIONS_UI_USE_CUSTOM_SCALE_TOOLTIP,
    },
}
-- }}}

for _,x in ipairs(AccountSettings.SettingSystemType) do
    AccountSettings.Default.settings[x] = {}
end

for _,x in ipairs(AccountSettings.SettingSystemType) do
    AccountSettings.Default.settingsBool[x] = {}
    for _, y in ipairs(AccountSettings.SettingIds[x]) do
        AccountSettings.Default.settingsBool[x][y] = true
    end
end

for _,x in ipairs(AccountSettings.ChatColors) do
    AccountSettings.Default.chatColors[x] = {}
end

function AccountSettings:SaveChatSettings()
    if ZO_ChatWindow and ZO_ChatWindow.container then
        local settings = ZO_ChatWindow.container.settings

        settings.width, settings.height = ZO_ChatWindow:GetDimensions()
        local _ _, settings.point, _, settings.relPoint, settings.x, settings.y = ZO_ChatWindow:GetAnchor(0)

        AccountSettings.sv.chatWindowSettings = ZO_ChatWindow.container.settings
        AccountSettings:Log ( AccountSettings.DEBUG_COLOR, "ChatWindowSettings " .. tostring( AccountSettings.sv.chatWindowSettings ) )
    end
end

function AccountSettings:CreateSettingsBool()
    local rtn = {
        [1] = {
            type = "checkbox",
            name = "Sync",
            tooltip = "Sync your settings once you choose whom to save settings on",
            default = AccountSettings.sv.sync,
            getFunc = function() return AccountSettings.sv.sync end,
            setFunc = function(newValue)
                AccountSettings.sv.sync = newValue
                if newValue then AccountSettings:Sync() end
            end,
            warning = "If you manually change your settings make sure to save it again with the button below."
        },

        [2] = {
            type = "checkbox",
            name = "Show Chat Save Button",
            tooltip = "A button to save chat settings",
            default = AccountSettings.sv.showChatIcon,
            getFunc = function() return AccountSettings.sv.showChatIcon end,
            setFunc = function(newValue)
                AccountSettings.sv.showChatIcon = newValue
                AccountSettings_SaveChat_Button:SetHidden(not AccountSettings.sv.showChatIcon)
            end,
        },

        [3] = {
            type = "button",
            name = "Save these settings",
            func = function() AccountSettings:SaveSettings() end,
            tooltip = "Once you click this it will save all the settings associated with this toon, then when you switch it will load all these settings.",
            width = "full",
            isDangerous = true,
            warning = "This will fully update what you had previously saved. If this is your first time, no worries. If this is your second time be weary that the previous data will be lost."
        },

        [4] = {
            type = "checkbox",
            name = "Log",
            tooltip = "Log messages for syncing/if you need to save/saved.",
            default = AccountSettings.sv.log,
            getFunc = function() return AccountSettings.sv.log end,
            setFunc = function(newValue)
                AccountSettings.sv.log = newValue
            end,
        },

        [5] = {
            type = "checkbox",
            name = "Debug",
            tooltip = "Show debug messages",
            default = AccountSettings.sv.debug,
            getFunc = function() return AccountSettings.sv.debug end,
            setFunc = function(newValue)
                AccountSettings.sv.debug = newValue
            end,
        },
        [6] = {
            type = "divider",
        },
        [7] = {
            type = "description",
            text = "|c33ccccYou will find many on/off switches to enable saving each setting type. If you would like for it to sync across your account leave it on, otherwise, turn it off. \n\n|r|ccccc33By defalt everything is on.|r",
        },
        [8] = {
            type = "divider",
        },
    }

    local index = 9

    for _,x in ipairs(AccountSettings.SettingSystemType) do
        local sub = {
            type = "submenu",
            name = AccountSettings.SettingSystemTypeString[x],
            controls = {}
        }
        local subIndex = 1

        for _, y in ipairs(AccountSettings.SettingIds[x]) do
            local cb = {
                type = "checkbox",
                name = EsoStrings[AccountSettings.SettingStrings[x][y]],
                tooltip = EsoStrings[AccountSettings.SettingTooltipStrings[x][y]],
                default = AccountSettings.Default.settingsBool[x][y],
                getFunc = function() return AccountSettings.sv.settingsBool[x][y] end,
                setFunc = function(newValue)
                    AccountSettings.sv.settingsBool[x][y] = newValue
                end,
            }

            sub.controls[subIndex] = cb
            subIndex = subIndex + 1
        end

        rtn[index] = sub
        index = index + 1
    end

    return rtn
end

function AccountSettings:SaveSettings()
    for _,x in ipairs(AccountSettings.SettingSystemType) do
        for _, y in ipairs(AccountSettings.SettingIds[x]) do
            local value = GetSetting(x,y)
            AccountSettings.sv.settings[x][y] = value
        end
    end

    for _,x in ipairs(AccountSettings.ChatColors) do
        local r,g,b = GetChatCategoryColor (x)
        local value = { r, g, b }

        AccountSettings.sv.chatColors[x] = value
    end

    AccountSettings.sv.tracked = true
    AccountSettings:Log ( AccountSettings.OKAY_COLOR, "Saved." )
end

function AccountSettings:Sync()
    if AccountSettings.sv.tracked and AccountSettings.sv.sync then
        for _,x in ipairs(AccountSettings.SettingSystemType) do
            for _, y in ipairs(AccountSettings.SettingIds[x]) do
                if AccountSettings.sv.settingsBool[x][y] then
                    SetSetting(x, y, AccountSettings.sv.settings[x][y])
                else
                    AccountSettings:Log ( AccountSettings.DEBUG_COLOR, "Ignoring : " .. AccountSettings.SettingStrings[x][y] )
                end
            end
        end

        for _,x in ipairs(AccountSettings.ChatColors) do
            SetChatCategoryColor ( x,
                AccountSettings.sv.chatColors[x][1],
                AccountSettings.sv.chatColors[x][2],
                AccountSettings.sv.chatColors[x][3]
            )
        end

        if ZO_ChatWindow and ZO_ChatWindow.container then
            local settings = AccountSettings.sv.chatWindowSettings
            if settings and ZO_ChatWindow and ZO_ChatWindow.container then
                ZO_ChatWindow:ClearAnchors()
                ZO_ChatWindow:SetAnchor(settings.point, nil, settings.relPoint, settings.x, settings.y)
                ZO_ChatWindow:SetDimensions(settings.width, settings.height)
                SharedChatContainer.LoadSettings(ZO_ChatWindow.container, settings)
            end
        end


        AccountSettings:Log ( AccountSettings.OKAY_COLOR, "Synced" )
    else
        AccountSettings:Log ( AccountSettings.ERROR_COLOR, "You must set a character to track first before you can sync" )
    end
end

function AccountSettings:Log(color, message)
    if color == AccountSettings.DEBUG_COLOR then
        if AccountSettings.sv.debug then
            d ( "|c"..tostring(color)..tostring(message).."|r" )
        end
    elseif AccountSettings.sv.log then
        d ( "|c"..tostring(color)..tostring(message).."|r" )
    end
end

-- Settings {{{
function AccountSettings:CreateSettingsWindow()
    local LAM = LibAddonMenu2

    local settingsWindowData = {
        type = "panel",
        name = AccountSettings.displayName,
        author = "|cff00ffJodynn|r",
        version = "".. AccountSettings.version,
        registerForRefresh = true,
        registerForDefaults = true,
        slashCommand = "/accountsettings"
    }

    local settingsOptionsData = AccountSettings:CreateSettingsBool()
    AccountSettings.sett = settingsOptionsData

    local settingsOptionPanel = LAM:RegisterAddonPanel(AccountSettings.name.."_LAM", settingsWindowData)
    LAM:RegisterOptionControls(AccountSettings.name.."_LAM", settingsOptionsData)
end
-- Settings }}}

EVENT_MANAGER:RegisterForEvent(AccountSettings.name, EVENT_ADD_ON_LOADED, function(eventCode, addonName) -- {{{
    if addonName ~= AccountSettings.name then return end

    AccountSettings.sv = ZO_SavedVars:NewAccountWide(AccountSettings.savedName, AccountSettings.version, nil, AccountSettings.Default)
    EVENT_MANAGER:UnregisterForEvent(AccountSettings.name, EVENT_ADD_ON_LOADED)

    AccountSettings:CreateSettingsWindow()

    SLASH_COMMANDS["/accountsync"] = AccountSettings.Sync

    AccountSettings_SaveChat_Button:SetHidden(not AccountSettings.sv.showChatIcon)
    AccountSettings_SaveChat_Button:SetHandler("OnClicked", function (self)
        AccountSettings:SaveChatSettings()
    end)
    AccountSettings_SaveChat_Button.data = { tooltipText = "Save current chat window settings ( size/position )" }
    AccountSettings_SaveChat_Button:SetHandler("OnMouseEnter", ZO_Options_OnMouseEnter)
    AccountSettings_SaveChat_Button:SetHandler("OnMouseExit", ZO_Options_OnMouseExit)

end) -- }}}

EVENT_MANAGER:RegisterForEvent(AccountSettings.name, EVENT_PLAYER_ACTIVATED , function(eventCode, initial) -- {{{
    zo_callLater ( AccountSettings.Sync, 5000 )
end) -- }}}
